version: '3'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"    # Expose FastAPI app (Uvicorn)
      - "8089:8089"    # Expose Locust web UI
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - fastapi-redis-net

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - fastapi-redis-net

networks:
  fastapi-redis-net:
    driver: bridge
